name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: {}

jobs:

  # --- JOB: prepare-test-reporting

  prepare-test-reporting:
    name: Prepare Test Reporting
    runs-on: ubuntu-latest

    steps:
    - name: Upload Event Payload
      uses: actions/upload-artifact@v3
      with:
        name: Event File
        path: ${{ github.event_path }}


  # --- JOB: build-and-test
  
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Get Sources
        uses: actions/checkout@v3

      - name: Get .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore Packages
        run: dotnet restore

      - name: Build Debug
        run: dotnet build -c Debug

      - name: Run Tests
        run: dotnet test --no-build --logger trx --results-directory out/test-results

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: out/test-results/*.trx
