name: CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      
      # Prepare
      - name: Install .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Get sources
        uses: actions/checkout@v2

      # Build and Test

      - name: Restore packages
        run: dotnet restore

      - name: Build Debug
        run: dotnet build --configuration Debug

      - name: Run tests
        run: dotnet test --no-build --collect "Code Coverage"

      # Build and Deploy

      - name: Build Release
        run: dotnet build --configuration Release

      - name: Publish to Production
        run: dotnet publish --configuration Release --no-build --no-self-contained /p:PublishProfile=Production.pubxml /p:Password="${{ secrets.DEPLOY_PASSWORD_PRODUCTION }}"
